# -*- coding: utf-8 -*-
"""practical 5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2A9zvyjM80LIU3hAg6bAzrvtu7B32rX
"""

#string indexing and slicing
#character-string,list,tuple

my_string='hello'
print(my_string[0])
print(my_string[3])
print(my_string[4])
print(my_string[-2])
print(my_string[-4])
#indexing

#slicing
my_string='hello'
print(my_string[1:4])
print(my_string[:3])
print(my_string[2:])
print(my_string[0:])

#step size
my_string='hello'
print(my_string[0:4:2])
print(my_string[-1::-1])
print(my_string[::-1])
print(my_string[2:4:2])

print(my_string[0:3:2])
print(my_string[1:4:3])
print(my_string[0:2:2])
print(my_string[-1:-5:-2])
print(my_string[-1:-4:2])

#datatype-mapping datatype............dictionaries(key,value pairs)
my_dict={'Name':'Anita','city':'jaipur'}
#my_dict={'key':'value','key2':'value2'......}
#curly braces
#elements in key value pairs
#key------unique and immutable

my_dict={'Name':'Anita','city':'jaipur','state':'Rajasthan','pin':302021}
#dict()constructor
my_dict=dict(name='anita',city='jaipur',age=20)

#accessing
#print(my_dict['lastname']) >>>>>>>>'error'
#print(my_dict.get('lastname'))  >>>>>>>>'error'

my_dict={'Name':'Anita','city':'jaipur','state':'Rajasthan','pin':302021}
print(my_dict.get('lastname','Not available write any other key'))

#modifying and updating the dictionary
my_dict['Name']='anu'
print(my_dict)

my_dict['age']=21
print(my_dict)